// Auto-generated by build_voc.py -- DO NOT EDIT
// Voice resource address & length definitions

#ifndef __VOC_H__
#define __VOC_H__

#define VOC_COUNT       4
#define VOC_MAX_ENTRIES 10
#define VOC_PART_SIZE   0x1B000u  // setuserbin partition size
#define VOC_TOC_ADDR    0x60000u  // TOC 头部地址

// 运行时从 Flash 读取 TOC 条目 (UART 升级后地址/长度可能已变化)
static inline bool voc_read_entry(u8 idx, u32 *p_addr, u32 *p_len) {
    if (idx >= VOC_MAX_ENTRIES) return false;
    extern uint os_spiflash_read(void *buf, u32 addr, uint len);
    u32 toc[2];
    os_spiflash_read(toc, VOC_TOC_ADDR + idx * 8, 8);
    *p_addr = toc[0];
    *p_len  = toc[1];
    return (*p_addr != 0 && *p_len != 0);
}

// 01_powon.mp3
#define VOC_POWON_ADDR     0x060050u
#define VOC_POWON_LEN      18195u

// 02_connected.mp3
#define VOC_CONNECTED_ADDR     0x064763u
#define VOC_CONNECTED_LEN      13155u

// 03_disconnect.mp3
#define VOC_DISCONNECT_ADDR     0x067AC6u
#define VOC_DISCONNECT_LEN      12867u

// 04_max_vol.mp3
#define VOC_MAX_VOL_ADDR     0x06AD09u
#define VOC_MAX_VOL_LEN      12435u

// 按索引的地址/长度数组 (索引 0 ~ VOC_COUNT-1)
#define VOC_ADDR(idx)  ((idx) < VOC_COUNT ? voc_addrs[idx] : 0)
#define VOC_LEN(idx)   ((idx) < VOC_COUNT ? voc_lens[idx]  : 0)

static const unsigned int voc_addrs[VOC_COUNT] = { 0x060050u, 0x064763u, 0x067AC6u, 0x06AD09u };
static const unsigned int voc_lens[VOC_COUNT]  = { 18195u, 13155u, 12867u, 12435u };

#endif // __VOC_H__
