// Auto-generated by build_voc.py -- DO NOT EDIT
// Voice resource address & length definitions

#ifndef __VOC_H__
#define __VOC_H__

#define VOC_COUNT       3
#define VOC_MAX_ENTRIES 10
#define VOC_PART_SIZE   0x1B000u  // setuserbin partition size

// 01_powon.mp3
#define VOC_POWON_ADDR     0x060050u
#define VOC_POWON_LEN      13155u

// 02_poweron.mp3
#define VOC_POWERON_ADDR     0x0633B3u
#define VOC_POWERON_LEN      19635u

// 03_poweronxx.mp3
#define VOC_POWERONXX_ADDR     0x068066u
#define VOC_POWERONXX_LEN      17475u

// 按索引的地址/长度数组 (索引 0 ~ VOC_COUNT-1)
#define VOC_ADDR(idx)  ((idx) < VOC_COUNT ? voc_addrs[idx] : 0)
#define VOC_LEN(idx)   ((idx) < VOC_COUNT ? voc_lens[idx]  : 0)

static const unsigned int voc_addrs[VOC_COUNT] = { 0x060050u, 0x0633B3u, 0x068066u };
static const unsigned int voc_lens[VOC_COUNT]  = { 13155u, 19635u, 17475u };

#endif // __VOC_H__
