"""
AB5605B voc.bin 构建工具
=======================
扫描 voc/ 目录中按文件名排序的 MP3 文件，
生成带 80 字节 TOC 头部的 voc.bin。

TOC 头部结构 (从 NOR Flash 0x60000 开始):
  偏移    大小   描述
  0x00    4B     语音0 的 FLASH 绝对地址 (u32 LE)
  0x04    4B     语音0 的数据长度 (u32 LE)
  0x08    4B     语音1 的 FLASH 绝对地址
  0x0C    4B     语音1 的数据长度
  ...
  0x48    4B     语音9 的 FLASH 绝对地址
  0x4C    4B     语音9 的数据长度
  --------80 字节头部结束--------
  0x50+          MP3 数据依次拼接

运行: python build_voc.py
  或:  python build_voc.py <voc_dir> <output_bin>
"""

import os
import sys
import struct

# ---- 配置常量 ----
BASE_FLASH_ADDR = 0x60000         # NOR Flash 起始地址
FLASH_PART_SIZE = 0x1B000         # setuserbin 分配的扇区大小 = 108 KB (110592 bytes)
HEADER_SIZE     = 80               # 10 条 × 8 字节 = 80 字节
MAX_ENTRIES     = 10               # 最多 10 条语音
DATA_OFFSET     = BASE_FLASH_ADDR + HEADER_SIZE  # 0x60050, 第一条 MP3 起始地址

# ---- 路径 (相对于 workspace 根目录) ----
def get_default_paths():
    """获取 voc 目录和输出文件的默认路径"""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    workspace  = os.path.dirname(script_dir)  # tools/ 的上一级 = workspace 根目录
    voc_dir    = os.path.join(workspace, "projects", "standard", "Output", "bin", "voc")
    output     = os.path.join(workspace, "projects", "standard", "Output", "bin", "voc.bin")
    header     = os.path.join(workspace, "projects", "standard", "voc.h")
    return voc_dir, output, header


def _make_macro_name(filename):
    """从文件名提取 C 宏名称: 01_powon.mp3 -> VOC_POWON"""
    name = os.path.splitext(filename)[0]                   # 去扩展名
    # 去掉前导数字和分隔符, 例如 "01_powon" -> "powon"
    while name and (name[0].isdigit() or name[0] in "_-"):
        name = name[1:]
    name = name.strip("_-") or "unnamed"
    # 转大写, 非字母数字下划线 -> 下划线
    macro = "VOC_"
    for ch in name.upper():
        if ch.isalnum():
            macro += ch
        else:
            macro += "_"
    return macro.rstrip("_")


def generate_voc_header(entries, header_path):
    """生成 voc.h 头文件, 包含每条语音的地址和长度宏定义"""
    lines = [
        "// Auto-generated by build_voc.py -- DO NOT EDIT",
        "// Voice resource address & length definitions",
        "",
        "#ifndef __VOC_H__",
        "#define __VOC_H__",
        "",
        f"#define VOC_COUNT       {len(entries)}",
        f"#define VOC_MAX_ENTRIES {MAX_ENTRIES}",
        f"#define VOC_PART_SIZE   0x{FLASH_PART_SIZE:05X}u  // setuserbin partition size",
        "",
    ]

    for idx, fname, addr, length in entries:
        macro = _make_macro_name(fname)
        lines.append(f"// {fname}")
        lines.append(f"#define {macro}_ADDR     0x{addr:06X}u")
        lines.append(f"#define {macro}_LEN      {length}u")
        lines.append("")

    # 也生成按索引的宏, 方便循环遍历
    lines.append("// 按索引的地址/长度数组 (索引 0 ~ VOC_COUNT-1)")
    lines.append(f"#define VOC_ADDR(idx)  ((idx) < VOC_COUNT ? voc_addrs[idx] : 0)")
    lines.append(f"#define VOC_LEN(idx)   ((idx) < VOC_COUNT ? voc_lens[idx]  : 0)")
    lines.append("")

    # 生成静态查找表
    addrs = ", ".join(f"0x{a:06X}u" for _, _, a, _ in entries)
    lens  = ", ".join(f"{l}u"       for _, _, _, l in entries)
    lines.append(f"static const unsigned int voc_addrs[VOC_COUNT] = {{ {addrs} }};")
    lines.append(f"static const unsigned int voc_lens[VOC_COUNT]  = {{ {lens} }};")
    lines.append("")
    lines.append("#endif // __VOC_H__")

    os.makedirs(os.path.dirname(header_path), exist_ok=True)
    with open(header_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"[OK] 生成 {header_path}")


def build_voc_body(voc_dir):
    """扫描 voc/ 目录, 返回 (voc_bin, entries) — 供 upgrade_tool 复用"""
    if not os.path.isdir(voc_dir):
        return None, []

    all_files   = sorted(os.listdir(voc_dir))
    mp3_files   = [f for f in all_files if f.lower().endswith(".mp3")]

    if len(mp3_files) == 0:
        return None, []
    if len(mp3_files) > MAX_ENTRIES:
        mp3_files = mp3_files[:MAX_ENTRIES]

    header    = bytearray(HEADER_SIZE)
    data_blob = bytearray()
    entries   = []

    for i, fname in enumerate(mp3_files):
        fpath   = os.path.join(voc_dir, fname)
        mp3_data = open(fpath, "rb").read()
        mp3_size = len(mp3_data)
        flash_addr = DATA_OFFSET + len(data_blob)
        struct.pack_into("<I", header, i * 8,       flash_addr)
        struct.pack_into("<I", header, i * 8 + 4,   mp3_size)
        data_blob.extend(mp3_data)
        entries.append((i, fname, flash_addr, mp3_size))

    voc_bin = header + data_blob
    total_size = len(voc_bin)
    if total_size > FLASH_PART_SIZE:
        return None, []

    return voc_bin, entries


def build_voc(voc_dir, output_path, header_path):
    """扫描 voc/ 目录, 生成带 TOC 头部的 voc.bin 和 voc.h"""

    if not os.path.isdir(voc_dir):
        print(f"[ERROR] voc 目录不存在: {voc_dir}")
        return False

    # 获取所有文件并按文件名排序
    all_files   = sorted(os.listdir(voc_dir))
    mp3_files   = [f for f in all_files if f.lower().endswith(".mp3")]

    if len(mp3_files) == 0:
        print(f"[ERROR] voc 目录中没有 .mp3 文件: {voc_dir}")
        return False

    if len(mp3_files) > MAX_ENTRIES:
        print(f"[WARN] voc 目录中有 {len(mp3_files)} 个 .mp3 文件, 只取前 {MAX_ENTRIES} 个")
        mp3_files = mp3_files[:MAX_ENTRIES]

    print(f"[INFO] 找到 {len(mp3_files)} 个语音文件:")

    # ---- 构建头部和数据块 ----
    header    = bytearray(HEADER_SIZE)   # 全部初始化为 0
    data_blob = bytearray()
    entries   = []                       # [(idx, fname, addr, len), ...] 给 voc.h 用

    for i, fname in enumerate(mp3_files):
        fpath   = os.path.join(voc_dir, fname)
        mp3_data = open(fpath, "rb").read()
        mp3_size = len(mp3_data)

        # 计算本条语音在 NOR Flash 中的绝对地址
        flash_addr = DATA_OFFSET + len(data_blob)

        # 写入 TOC 条目: [addr:u32][len:u32]
        struct.pack_into("<I", header, i * 8,       flash_addr)
        struct.pack_into("<I", header, i * 8 + 4,   mp3_size)

        # 拼接数据
        data_blob.extend(mp3_data)

        entries.append((i, fname, flash_addr, mp3_size))
        print(f"  [{i}] {fname:30s}  addr=0x{flash_addr:06X}  size={mp3_size:>6d} bytes")

    # 未使用的条目保持为 0 (header 初始化时已全零)

    # ---- 大小检查 ----
    total_size = HEADER_SIZE + len(data_blob)
    pct = total_size * 100.0 / FLASH_PART_SIZE
    print(f"\n[INFO] voc.bin 大小: {total_size} / {FLASH_PART_SIZE} bytes ({pct:.1f}%)")

    if total_size > FLASH_PART_SIZE:
        over = total_size - FLASH_PART_SIZE
        print(f"[ERROR] voc.bin 超出分区限制 {over} 字节!")
        print(f"        请减少语音文件大小或调整 setuserbin 分配 (当前 0x{FLASH_PART_SIZE:X})")
        return False

    # ---- 写入 voc.bin ----
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "wb") as f:
        f.write(header)
        f.write(data_blob)

    print(f"\n[OK] 生成 {output_path}")
    print(f"     头部: {HEADER_SIZE} 字节  |  数据: {len(data_blob)} 字节  |  总计: {total_size} 字节 ({pct:.1f}%)")
    print(f"     剩余空间: {FLASH_PART_SIZE - total_size} 字节 ({(FLASH_PART_SIZE - total_size)/1024:.1f} KB)")

    # ---- 生成 voc.h ----
    if header_path:
        generate_voc_header(entries, header_path)

    return True


if __name__ == "__main__":
    voc_dir, output, header = get_default_paths()

    # 允许命令行覆盖路径
    if len(sys.argv) >= 2:
        voc_dir = sys.argv[1]
    if len(sys.argv) >= 3:
        output = sys.argv[2]
    if len(sys.argv) >= 4:
        header = sys.argv[3]

    success = build_voc(voc_dir, output, header)
    sys.exit(0 if success else 1)
